#!/usr/bin/with-contenv bash

#Make prosody self signed certificate trusted
cp -Rf /config/prosody/certs/*.crt /usr/local/share/ca-certificates/
cp -Rf /config/prosody/certs/*.key /usr/local/share/ca-certificates/
update-ca-certificates


JAVA_SYS_PROPS="-Dnet.java.sip.communicator.SC_HOME_DIR_LOCATION=/ -Dnet.java.sip.communicator.SC_HOME_DIR_NAME=/config/jicofo -Djava.util.logging.config.file=/config/jicofo/logging.properties"
DAEMON=/usr/share/jicofo/jicofo.sh
DAEMON_DIR=/usr/share/jicofo/
DAEMON_OPTS="--domain=$XMPP_DOMAIN --host=$XMPP_SERVER --secret=$JICOFO_COMPONENT_SECRET --user_name=$JICOFO_AUTH_USER --user_domain=$XMPP_AUTH_DOMAIN --user_password=$JICOFO_AUTH_PASSWORD"

exec s6-setuidgid jicofo /bin/bash -c "cd $DAEMON_DIR; JAVA_SYS_PROPS=\"$JAVA_SYS_PROPS\" exec $DAEMON $DAEMON_OPTS"
