apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: videobridge
  name: videobridge
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: videobridge
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.network/meet.jitsi: "true"
        io.kompose.service: videobridge
    spec:
      containers:
      - image: videobridge
        imagePullPolicy: ""
        name: videobridge
        ports:
        - containerPort: 10000
          protocol: UDP
        - containerPort: 4443
        resources: {}
        volumeMounts:
        - mountPath: /config
          name: videobridge-claim0
      hostname: videobridge
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: videobridge-claim0
        persistentVolumeClaim:
          claimName: videobridge-claim0
status: {}
