#!/usr/bin/with-contenv bash
export PROSODY_CFG="/etc/prosody/prosody.cfg.lua"
export CFG_CONFIGDIR="/etc/prosody"
export CFG_DATADIR="/config/data"

if [[ ! -f /etc/prosody/saslauthd.conf ]]; then
  tpl /defaults/saslauthd.conf > /etc/prosody/saslauthd.conf
  mkdir -pm777 /var/run/saslauthd
  adduser prosody sasl
  echo >> /etc/ldap/ldap.conf "TLS_REQCERT allow"
fi

if [[ ! -d /config/data ]]; then
    mkdir -pm 750 /config/data
    chown -R prosody /config/data
fi

if [[ "$(stat -c %U /config)" != "prosody" ]]; then
    chown -R prosody /etc/prosody
    chmod -R a+r /etc/prosody
fi

if [[ "$(stat -c %U /prosody-plugins)" != "prosody" ]]; then
    chown -R prosody /prosody-plugins
    chmod -R a+r /prosody-plugins
fi

if [[ "$(stat -c %U /prosody-plugins-custom)" != "prosody" ]]; then
    chown -R prosody /prosody-plugins-custom
    chmod -R a+r /prosody-plugins-custom
fi

    cp -r /defaults/* /etc/prosody
    envsubst < /defaults/prosody.cfg.lua > /etc/prosody/prosody.cfg.lua
    envsubst < /defaults/conf.d/jitsi-meet.cfg.lua > /etc/prosody/conf.d/jitsi-meet.cfg.lua

    prosodyctl --config $PROSODY_CFG register $JICOFO_AUTH_USER    $XMPP_AUTH_DOMAIN         $JICOFO_AUTH_PASSWORD
    prosodyctl --config $PROSODY_CFG register $JVB_AUTH_USER       $XMPP_INTERNAL_MUC_DOMAIN $JVB_AUTH_PASSWORD
    prosodyctl --config $PROSODY_CFG register $JIBRI_XMPP_USER     $XMPP_INTERNAL_MUC_DOMAIN $JIBRI_XMPP_PASSWORD
    prosodyctl --config $PROSODY_CFG register $JIGASI_XMPP_USER    $XMPP_INTERNAL_MUC_DOMAIN $JIGASI_XMPP_PASSWORD
    prosodyctl --config $PROSODY_CFG register $JIBRI_RECORDER_USER $XMPP_RECORDER_DOMAIN     $JIBRI_RECORDER_PASSWORD
    
    mkdir -p /etc/prosody/certs
    if [[ ! -f /etc/prosody/certs/$XMPP_DOMAIN.crt ]]; then
        # echo for using all default values
        echo | prosodyctl --config $PROSODY_CFG cert generate $XMPP_DOMAIN
    fi

    if [[ ! -f /etc/prosody/certs/$XMPP_AUTH_DOMAIN.crt ]]; then
        # echo for using all default values
        echo | prosodyctl --config $PROSODY_CFG cert generate $XMPP_AUTH_DOMAIN
    fi

    if [[ ! -f /etc/prosody/certs/$XMPP_MUC_DOMAIN.crt ]]; then
        # echo for using all default values
        echo | prosodyctl --config $PROSODY_CFG cert generate $XMPP_MUC_DOMAIN
    fi

    if [[ ! -f /etc/prosody/certs/$XMPP_INTERNAL_MUC_DOMAIN.crt ]]; then
        # echo for using all default values
        echo | prosodyctl --config $PROSODY_CFG cert generate $XMPP_INTERNAL_MUC_DOMAIN
    fi

# certs will be created in /config/data
mv /config/data/*.{crt,key} /etc/prosody/certs/ || true
rm -f /config/data/*.cnf