#!/usr/bin/with-contenv bash

#export LOCAL_ADDRESS=$(ip addr show dev "$(ip route|awk '/^default/ { print $5 }')" | grep -oP '(?<=inet\s)\d+(\.\d+){3}')
export LOCAL_ADDRESS=`hostname -i`

if [[ -z $JVB_AUTH_PASSWORD ]]; then
    echo 'FATAL ERROR: JVB auth password must be set'
    exit 1
fi

OLD_JVB_AUTH_PASSWORD=passw0rd
if [[ "$JVB_AUTH_PASSWORD" == "$OLD_JVB_AUTH_PASSWORD" ]]; then
    echo 'FATAL ERROR: JVB auth password must be changed, check the README'
    exit 1
fi

envsubst < /defaults/sip-communicator.properties > /etc/jitsi/videobridge/sip-communicator.properties
envsubst < /defaults/jvb.conf > /etc/jitsi/videobridge/jvb.conf
envsubst < /defaults/config > /etc/jitsi/videobridge/config
cp /defaults/logging.properties /etc/jitsi/videobridge/


chown -R jvb:jitsi /etc/jitsi/videobridge/
