#!/usr/bin/with-contenv bash

#export LOCAL_ADDRESS=$(ip addr show dev "$(ip route|awk '/^default/ { print $5 }')" | grep -oP '(?<=inet\s)\d+(\.\d+){3}')
export LOCAL_ADDRESS=`hostname -i`

envsubst < /defaults/sip-communicator.properties > /etc/jitsi/videobridge/sip-communicator.properties
envsubst < /defaults/jvb.conf > /etc/jitsi/videobridge/jvb.conf
#envsubst < /defaults/config > /etc/jitsi/videobridge/config
cp /defaults/logging.properties /etc/jitsi/videobridge/

chown -R jvb:jitsi /etc/jitsi/videobridge/
