#!/usr/bin/with-contenv bash
#Make prosody self signed certificate trusted
cp -Rf /config/prosody/certs/*.crt /usr/local/share/ca-certificates/
cp -Rf /config/prosody/certs/*.key /usr/local/share/ca-certificates/
update-ca-certificates

mkdir -p /etc/jitsi/jicofo
envsubst < /defaults/config > /etc/jitsi/jicofo/config
envsubst < /defaults/sip-communicator.properties > /etc/jitsi/jicofo/sip-communicator.properties
cp /defaults/logging.properties /etc/jitsi/jicofo


chown -R jicofo:jitsi /etc/jitsi/jicofo
chmod -R a+r /etc/jitsi/jicofo
